- include_tasks: command_line_tools.yml

- name: Check if homebrew is available
  block:
    - name: try using homebrew in check_mode (no changes)
      homebrew:
        update_homebrew: true
      check_mode: true

  rescue:
    - name: No homebrew
      fail:
        msg: Homebrew is missing, install from web

- name: Reset the Homebrew Library repo
  git:
    repo=https://github.com/Homebrew/brew.git
    dest=/usr/local/Homebrew/Library
    clone=no
    update=yes
    force=yes

- name: Update Homebrew (first try may fail)
  homebrew: update_homebrew=yes
  become: no
  ignore_errors: yes

- name: Update Homebrew
  homebrew: update_homebrew=yes
  become: no

- name: Tap hmarr
  community.general.homebrew_tap:
    name: homebrew/hmarr
    url: 'git@github.com:hmarr/homebrew-tap'

- name: Install brew packages
  homebrew:
    name:
      - mas
      - tmux
      - lf
      - neovim
      - rust
      - ruff
      - codeowners
      - python@3.13
    state: present

- name: Install casks
  community.general.homebrew_cask:
    name:
      - stats
      - monitorcontrol
    state: present

- name: Install Mac Apps
  community.general.mas:
    id:
      - 732710998  # enpass
    state: present

- name: Symlink python binary
  file:
    src: /opt/homebrew/bin/python3
    dest: /usr/local/bin/python
    state: link
  become: true

- name: Symlink pip binary
  file:
    src: /opt/homebrew/bin/pip3
    dest: /usr/local/bin/pip3
    state: link
  become: true
