#!@bashInteractive@/bin/bash

if [[ "$1" != "--rcfile" ]]; then
  echo "Something is wrong: invoked as:" >&2
  echo "$0 $@" >&2
  exit 1
fi

rcfile="$2"
source "$rcfile"

exec @zsh@/bin/zsh --emulate zsh

