
- name: Create .config directory if it does not exist
  ansible.builtin.file:
    path: "{{ homedir }}/.config"
    state: directory
    mode: '0755'

- name: Create .config/nvim directory if it does not exist
  ansible.builtin.file:
    path: "{{ homedir }}/.config/nvim"
    state: directory
    mode: '0755'

- name: Copy nvim Lua config
  copy:
    src: "{{ role_path }}/files/nvim/init.lua"
    dest: "{{ homedir }}/.config/nvim/init.lua"
    owner: "{{ username }}"
    group: "{{ usergrp }}"

- name: Check if nvim conf exists
  stat:
    path: "{{ homedir }}/.config/nvim"
  register: nvimconf

- name: Check if nvim colors exists
  stat:
    path: "{{ homedir }}/.config/nvim/colors/molokai.vim"
  register: nvimcolors

- name: Copy nvim confs
  copy:
    src: "{{ role_path }}/files/vim/"
    dest: "{{ homedir }}/.config/nvim"
    owner: "{{ username }}"
    group: "{{ usergrp }}"
  when: not nvimcolors.stat.exists

- name: Copy /opt
  copy:
    src: "{{ role_path }}/files/opt"
    dest: "{{ homedir }}/"
    owner: "{{ username }}"
    group: "{{ usergrp }}"
    mode: u+x

- name: Install global python packages
  ansible.builtin.pip:
    executable: /opt/homebrew/bin/pip3
    name:
      - black==23.10.1
      - click==8.0.2
      - jedi-language-server==0.43.1
      - flake8==6.0.0
      - flake8-isort==6.0.0
      - isort==5.11.4
      - pynvim==0.4.3
      - virtualenv==20.26.5
    extra_args: "-U --break-system-packages"

- name: Check if pyenv conf exists
  stat:
    path: "{{ homedir }}/.pyenv"
  register: pyenvconf

- name: Install pyenv
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{ homedir }}/.pyenv"
    update: yes

- name: Install pyenv-virtualenv
  git:
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    dest: "{{ homedir }}/.pyenv/plugins/pyenv-virtualenv"
    update: no
  when: not pyenvconf.stat.exists

- name: Install Pyenv version 3.13
  command: pyenv install -s 3.13.1

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "{{ homedir }}/.oh-my-zsh"

- name: Copy zshrc
  copy:
    src: "{{ role_path }}/files/zshrc"
    dest: "{{ homedir }}/.zshrc"
    owner: "{{ username }}"
    group: "{{ usergrp }}"
